// s06 Context Compact: don't delete history -- relocate detail so the loop
// can keep going past the model's effective window.
//
// Strategy here is intentionally simple:
//   - keep the most recent N message-pairs verbatim
//   - summarize everything before into a single synthetic assistant message
//
// The summary is generated by a cheap secondary model call. For this
// scaffold we use the same model but in a one-shot, tool-less mode.

import type { ApiMessage } from "../types.js";
import { callModel } from "../llm.js";

const KEEP_RECENT_TURNS = 6; // pairs at the tail to leave untouched
const COMPACT_TRIGGER_TOKENS = 30_000; // call when cumulative tokens exceed this

export function shouldCompact(tokensUsed: number, messages: ApiMessage[]): boolean {
  return tokensUsed > COMPACT_TRIGGER_TOKENS && messages.length > KEEP_RECENT_TURNS * 2;
}

export async function compact(messages: ApiMessage[]): Promise<ApiMessage[]> {
  const tail = messages.slice(-KEEP_RECENT_TURNS * 2);
  const head = messages.slice(0, messages.length - tail.length);
  if (head.length === 0) return messages;

  const transcript = head
    .map((m) => {
      const content =
        typeof m.content === "string"
          ? m.content
          : m.content
              .map((c) => {
                if (c.type === "text") return c.text;
                if (c.type === "tool_use") return `[tool_use ${c.name}]`;
                if (c.type === "tool_result")
                  return `[tool_result ${typeof c.content === "string" ? c.content : "..."}]`;
                return "";
              })
              .join("\n");
      return `${m.role.toUpperCase()}: ${content}`;
    })
    .join("\n\n");

  const resp = await callModel({
    system:
      "Summarize the following agent transcript. Preserve: user goals, decisions made, " +
      "files touched, tool outputs that matter for later work, and any unresolved items. " +
      "Drop chit-chat and routine confirmations. Be dense.",
    messages: [{ role: "user", content: transcript }],
    tools: [],
  });

  const summaryText = resp.content
    .filter((b): b is { type: "text"; text: string; citations?: any } => b.type === "text")
    .map((b) => b.text)
    .join("\n");

  const summaryMessage: ApiMessage = {
    role: "assistant",
    content: `[compacted earlier turns]\n${summaryText}`,
  };

  return [summaryMessage, ...tail];
}
